### ISSUE TITLE
How to support the RTMP, RTSP protocol live?

### ISSUE THREAD

**Issue by xhzengAIB** [JV17/YoutubePlayer#1]
Hi！ @JV17 

HLS Support is very good. But RTMP / RTSP protocal streaming not support playing.

Jack

**Comment by JV17** [comment]
Hi @xhzengAIB,

Yah, it's not supported. I don't think, I will be supporting it unless Youtube supports it within their helper library. 

But feel free to contribute and I could check if Youtube won't complain about it. :)

JV

**Comment by xhzengAIB** [comment]
Hi! @JV17 
Thank you! i'll use other method due with The problem.
I close this issue
Jack
