### ISSUE TITLE
Player restarting while going for another video

### ISSUE THREAD

**Issue by kdpuvvadi** [JV17/YoutubePlayer#3]
Thank for you code, 
I've added a playlist id and videos are playing very well for  PlayWithPlaylistID, when i'm using PlayWithVideoID by appending videoDI , it playing but when i'm appeding another ID to the player, Player is closing and reopening with new video ID i've provided, is it possible to play videos continuously by dynamically providing Video IDs using PlayWithVideoID without reopening player every time?

**Comment by JV17** [comment]
No, you have to first load a video or playlist and then load the video ids to the player..
```
// loading playlist to video player
[self.player loadPlayerWithPlaylistId:@"PLEE58C6029A8A6ADE"];
    
NSArray *videoList = @[@"ILljLDHcxjU", @"jcKoyA872uE", @"B8LUXGtTSaU", @"ZW2muvIKNh4"];
    
[self.player loadPlaylistByVideos:videoList index:0 startSeconds:0.0 suggestedQuality:kYTPlaybackQualityHD720];
```

I will work on a better approach soon if you have one please feel free to contribute...

**Comment by JV17** [comment]
So, I have implemented a function call `loadPlayerWithVideosId` which you can call and pass the list of videos ids that you would like play in an `NSArray` and it will load all those videos to the player..

Example,
```objc
// loading a set of videos to the player
    NSArray *videoList = @[@"m2d0ID-V9So", @"c7lNU4IPYlk"];
    [self.player loadPlayerWithVideosId:videoList];
```

I hope this helps!

**Comment by kdpuvvadi** [comment]
Thank you for reply, THanx for your time, It solved my issue
