### ISSUE TITLE
showinfo does not work properly

### ISSUE THREAD

**Issue by Goro-Otsubo** [JV17/YoutubePlayer#4]
I found out that "showing" parameter does not work correctly.

Modifying YTPlayerView.m like below will fix the issue.

------
-(BOOL)showinfo {
    //return _fullscreen;
    return _showinfo;
}

-(void)setShowinfo:(BOOL)showinfo {
    
    if(showinfo == YES) {
        [self.dicParameters setObject:@(1) forKey:@"showinfo"];
    }
    else{
        [self.dicParameters setObject:@(0) forKey:@"showinfo"];
    }
    _showinfo = showinfo;
}

**Comment by JV17** [comment]
@Goro-Otsubo Thanks for spotting that issue, it might has been an typo mistake from my end..
