### ISSUE TITLE
There is 2 warning comes...

### ISSUE THREAD

**Issue by BhavinBhadani** [JV17/YoutubePlayer#5]
In methods `loadPlayerWithVideosURL` and `loadPlayerWithVideosID` ....there is warning 
      
       Incompatible pointer to integer conversion returning 'void *' from a function with result type 'BOOL' (aka 'signed char')  

Because its return type is Bool and you return it as void..please solve this

**Comment by JV17** [comment]
Thanks for catching that one.. The fix will be included in the next release. 
Cheers!

**Comment by BhavinBhadani** [comment]
Ok...so for now I just make it bool ..

**Comment by JV17** [comment]
Closing the ticket because the issue has been solved.
